import { drinkThumbPath, type ViniciusDrink } from './viniciusDrinksCarta';

export type IbaCategory = 'Inesquecíveis' | 'Clássicos Contemporâneos' | 'Nova Era';

type IbaDef = Omit<ViniciusDrink, 'imageUrl'> & { ibaCategory: IbaCategory };

function iba(def: IbaDef): ViniciusDrink {
  const { ibaCategory, ...drink } = def;
  return {
    ...drink,
    category: drink.category ?? `IBA · ${ibaCategory}`,
    imageUrl: drinkThumbPath(drink.slug),
  };
}

const MIXED = 'Drink misturado (não batido)!';
const SHAKEN = 'Drink batido!';
const BUILT = 'Drink montado (não batido)!';

/** Coquetéis oficiais IBA ausentes da carta padrão e das sugestões personalizadas. */
export const IBA_SUGGESTION_DRINKS: ViniciusDrink[] = [
  // —— Inesquecíveis ——
  iba({
    slug: 'alexander',
    title: 'Alexander',
    tagline: 'Conhaque, creme de cacau e creme — sedoso e clássico.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['30ml de Conhaque', '30ml de Creme de cacau', '30ml de Creme de leite', 'Gelo'],
    steps: ['Bata todos os ingredientes com gelo;', 'Coe para taça de coquetel;', 'Polvilhe noz-moscada se quiser.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'americano',
    title: 'Americano',
    tagline: 'Campari, vermute doce e soda — amargo e refrescante.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['30ml de Campari', '30ml de Vermute Rosso', 'Soda', 'Gelo', 'Rodela de limão'],
    steps: ['Gele o copo;', 'Acrescente Campari e vermute;', 'Complete com soda;', 'Decore com limão.'],
    notes: MIXED,
  }),
  iba({
    slug: 'angel-face',
    title: 'Angel Face',
    tagline: 'Gin, brandy de damasco e calvados em partes iguais.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['30ml de Gin', '30ml de Brandy de damasco', '30ml de Calvados', 'Gelo'],
    steps: ['Misture com gelo;', 'Coe para taça gelada.'],
    notes: MIXED,
  }),
  iba({
    slug: 'aviation',
    title: 'Aviation',
    tagline: 'Gin, maraschino, violeta e limão — floral e seco.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['50ml de Gin', '15ml de Licor Maraschino', '10ml de Crème de violette', 'Suco de 1/2 limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça de coquetel.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'between-the-sheets',
    title: 'Between the Sheets',
    tagline: 'Rum branco, conhaque, triple sec e limão.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['30ml de Rum branco', '30ml de Conhaque', '30ml de Triple sec', 'Suco de 1/2 limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça gelada.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'boulevardier',
    title: 'Boulevardier',
    tagline: 'Whisky, vermute rosso e Campari — Negroni de whisky.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['45ml de Whisky', '30ml de Vermute Rosso', '30ml de Campari', 'Gelo'],
    steps: ['Misture com gelo;', 'Sirva no copo old fashioned;', 'Decore com casca de laranja.'],
    notes: MIXED,
  }),
  iba({
    slug: 'brandy-crusta',
    title: 'Brandy Crusta',
    tagline: 'Brandy, curaçau, limão e bitter — copo com crosta de açúcar.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['50ml de Brandy', '15ml de Curaçau', 'Suco de 1/2 limão', '1 dash de bitter', 'Gelo'],
    steps: ['Umedeça a borda da taça e passe no açúcar;', 'Bata os líquidos com gelo;', 'Coe para a taça.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'casino',
    title: 'Casino',
    tagline: 'Gin, maraschino, bitter de laranja e limão.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['40ml de Gin', '10ml de Maraschino', '1 dash de bitter de laranja', 'Suco de 1/2 limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça gelada.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'clover-club',
    title: 'Clover Club',
    tagline: 'Gin, limão, xarope de framboesa e clara de ovo.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['50ml de Gin', 'Suco de 1/2 limão', '15ml de Xarope de framboesa', 'Clara de 1 ovo', 'Gelo'],
    steps: ['Bata seco (sem gelo) para espumar;', 'Acrescente gelo e bata de novo;', 'Coe para taça.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'hanky-panky',
    title: 'Hanky Panky',
    tagline: 'Gin, vermute doce e Fernet — amargo e aromático.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['45ml de Gin', '45ml de Vermute Rosso', '7ml de Fernet-Branca', 'Gelo'],
    steps: ['Misture com gelo;', 'Coe para taça ou sirva no copo.'],
    notes: MIXED,
  }),
  iba({
    slug: 'john-collins',
    title: 'John Collins',
    tagline: 'Gin, limão, xarope e soda — irmão do Tom Collins.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['50ml de Gin', 'Suco de 1 limão', '1/2 dose de xarope de açúcar', 'Soda', 'Gelo'],
    steps: ['Misture gin, limão e xarope com gelo;', 'Complete com soda em copo alto.'],
    notes: MIXED,
  }),
  iba({
    slug: 'last-word',
    title: 'Last Word',
    tagline: 'Gin, Chartreuse verde, maraschino e limão — partes iguais.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['22ml de Gin', '22ml de Chartreuse verde', '22ml de Maraschino', '22ml de Suco de limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça gelada.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'martinez',
    title: 'Martinez',
    tagline: 'Precursor do Martini — gin, vermute doce e maraschino.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['45ml de Gin', '45ml de Vermute Rosso', '10ml de Maraschino', '2 dashes de bitter de laranja', 'Gelo'],
    steps: ['Misture com gelo;', 'Coe para taça de coquetel.'],
    notes: MIXED,
  }),
  iba({
    slug: 'mary-pickford',
    title: 'Mary Pickford',
    tagline: 'Rum branco, abacaxi, grenadine e maraschino.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['60ml de Rum branco', '60ml de Suco de abacaxi', '10ml de Grenadine', '10ml de Maraschino', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça gelada.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'monkey-gland',
    title: 'Monkey Gland',
    tagline: 'Gin, suco de laranja, grenadine e absinto.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['50ml de Gin', '50ml de Suco de laranja', '10ml de Grenadine', '1 dash de Absinto', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'paradise',
    title: 'Paradise',
    tagline: 'Gin, brandy de damasco e suco de laranja.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['30ml de Gin', '15ml de Brandy de damasco', '15ml de Suco de laranja', 'Suco de 1/2 limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'planters-punch',
    title: "Planter's Punch",
    tagline: 'Rum jamaicano, limão e cana — tropical clássico.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['60ml de Rum', 'Suco de 1 limão', '30ml de Xarope de cana', 'Gelo', '1 dash de bitter'],
    steps: ['Misture rum, limão e xarope com gelo;', 'Complete com água com gás se quiser;', 'Decore com fruta.'],
    notes: MIXED,
  }),
  iba({
    slug: 'porto-flip',
    title: 'Porto Flip',
    tagline: 'Brandy, porto ruby e gema — cremoso e encorpado.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['15ml de Brandy', '45ml de Porto ruby', '1 Gema de ovo', '1 colher de açúcar', 'Gelo'],
    steps: ['Bata todos os ingredientes com gelo;', 'Coe para taça pequena.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'ramos-fizz',
    title: 'Ramos Gin Fizz',
    tagline: 'Gin, limão, creme, clara e soda — espuma sedosa.',
    ibaCategory: 'Inesquecíveis',
    ingredients: [
      '45ml de Gin',
      'Suco de 1/2 limão',
      '15ml de Xarope de açúcar',
      '30ml de Creme de leite',
      'Clara de 1 ovo',
      'Soda',
      '2 dashes de água de flor de laranjeira',
      'Gelo',
    ],
    steps: ['Bata longamente com gelo;', 'Coe para copo alto sem gelo;', 'Complete com soda.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'remember-the-maine',
    title: 'Remember the Maine',
    tagline: 'Rye whisky, vermute, cherry brandy e absinto.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['60ml de Rye whisky', '22ml de Vermute Rosso', '15ml de Cherry brandy', '1 dash de Absinto', 'Gelo'],
    steps: ['Misture com gelo;', 'Coe para taça gelada.'],
    notes: MIXED,
  }),
  iba({
    slug: 'rusty-nail',
    title: 'Rusty Nail',
    tagline: 'Scotch whisky e Drambuie — simples e aquecedor.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['45ml de Scotch whisky', '25ml de Drambuie', 'Gelo'],
    steps: ['Misture com gelo no copo old fashioned.'],
    notes: MIXED,
  }),
  iba({
    slug: 'sazerac',
    title: 'Sazerac',
    tagline: 'Rye ou conhaque, absinto e Peychaud — ícone de Nova Orleans.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['60ml de Rye whisky ou Conhaque', '1 colher de açúcar', '3 dashes de Peychaud bitters', 'Absinto', 'Gelo'],
    steps: ['Enxágue a taça com absinto;', 'Misture whisky, açúcar e bitter com gelo;', 'Coe para a taça.'],
    notes: MIXED,
  }),
  iba({
    slug: 'sidecar',
    title: 'Sidecar',
    tagline: 'Conhaque, triple sec e limão — clássico francês.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['50ml de Conhaque', '20ml de Triple sec', '20ml de Suco de limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça com borda de açúcar.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'stinger',
    title: 'Stinger',
    tagline: 'Conhaque e crème de menta — after-dinner clássico.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['50ml de Conhaque', '20ml de Crème de menta branca', 'Gelo'],
    steps: ['Misture com gelo;', 'Coe para taça gelada.'],
    notes: MIXED,
  }),
  iba({
    slug: 'tuxedo',
    title: 'Tuxedo',
    tagline: 'Gin, vermute seco, maraschino, bitter e absinto.',
    ibaCategory: 'Inesquecíveis',
    ingredients: [
      '30ml de Gin',
      '30ml de Vermute Extra Dry',
      '10ml de Maraschino',
      '1 dash de bitter',
      '1 dash de Absinto',
      'Gelo',
    ],
    steps: ['Misture com gelo;', 'Coe para taça martini.'],
    notes: MIXED,
  }),
  iba({
    slug: 'vieux-carre',
    title: 'Vieux Carré',
    tagline: 'Rye, conhaque, vermute, Bénédictine e Peychaud.',
    ibaCategory: 'Inesquecíveis',
    ingredients: [
      '30ml de Rye whisky',
      '30ml de Conhaque',
      '30ml de Vermute Rosso',
      '10ml de Bénédictine',
      '2 dashes de Peychaud bitters',
      'Gelo',
    ],
    steps: ['Misture com gelo;', 'Sirva no copo old fashioned.'],
    notes: MIXED,
  }),
  iba({
    slug: 'white-lady',
    title: 'White Lady',
    tagline: 'Gin, triple sec e limão — sour seco e elegante.',
    ibaCategory: 'Inesquecíveis',
    ingredients: ['50ml de Gin', '20ml de Triple sec', '20ml de Suco de limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça gelada.'],
    notes: SHAKEN,
  }),

  // —— Clássicos Contemporâneos ——
  iba({
    slug: 'bellini',
    title: 'Bellini',
    tagline: 'Espumante e purê de pêssego — brunch italiano.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['100ml de Vinho espumante', '50ml de Purê de pêssego', 'Gelo opcional'],
    steps: ['Coloque o purê na taça;', 'Complete delicadamente com espumante.'],
    notes: BUILT,
  }),
  iba({
    slug: 'black-russian',
    title: 'Black Russian',
    tagline: 'Vodka e licor de café — forte e direto.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['50ml de Vodka', '20ml de Licor de café', 'Gelo'],
    steps: ['Misture com gelo no copo old fashioned.'],
    notes: MIXED,
  }),
  iba({
    slug: 'cardinale',
    title: 'Cardinale',
    tagline: 'Gin, vermute seco e Campari — seco e amargo.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['40ml de Gin', '20ml de Vermute Extra Dry', '20ml de Campari', 'Gelo'],
    steps: ['Misture com gelo;', 'Coe para taça de coquetel.'],
    notes: MIXED,
  }),
  iba({
    slug: 'champagne-cocktail',
    title: 'Champagne Cocktail',
    tagline: 'Espumante, açúcar, bitter e conhaque — festivo.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['1 cubo de açúcar', '2 dashes de bitter', '10ml de Conhaque', 'Espumante', 'Cereja'],
    steps: ['Umedeça o açúcar com bitter no copo;', 'Acrescente conhaque;', 'Complete com espumante gelado.'],
    notes: BUILT,
  }),
  iba({
    slug: 'corpse-reviver-2',
    title: 'Corpse Reviver #2',
    tagline: 'Gin, limão, Cointreau, Lillet e absinto — prova de vida.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['30ml de Gin', '30ml de Cointreau', '30ml de Vermouth Lillet', '30ml de Suco de limão', '1 dash de Absinto', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça gelada.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'cosmopolitan',
    title: 'Cosmopolitan',
    tagline: 'Vodka, triple sec, cranberry e limão.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['40ml de Vodka', '15ml de Triple sec', '30ml de Suco de cranberry', '15ml de Suco de limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça martini.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'french-connection',
    title: 'French Connection',
    tagline: 'Conhaque e amaretto — after-dinner simples.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['35ml de Conhaque', '35ml de Amaretto', 'Gelo'],
    steps: ['Misture com gelo no copo old fashioned.'],
    notes: MIXED,
  }),
  iba({
    slug: 'garibaldi',
    title: 'Garibaldi',
    tagline: 'Campari espumado com suco de laranja fresco.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['45ml de Campari', '120ml de Suco de laranja fresco', 'Gelo'],
    steps: ['Gele o copo alto;', 'Acrescente Campari;', 'Complete com laranja espumada na hora.'],
    notes: BUILT,
  }),
  iba({
    slug: 'grasshopper',
    title: 'Grasshopper',
    tagline: 'Crème de menta, cacau branco e creme — sobremesa líquida.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['20ml de Crème de menta verde', '20ml de Crème de cacao branco', '20ml de Creme de leite', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça de sobremesa.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'hemingway-special',
    title: 'Hemingway Special',
    tagline: 'Rum, maraschino, grapefruit e limão — sem açúcar.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['60ml de Rum', '15ml de Maraschino', '40ml de Suco de grapefruit', '15ml de Suco de limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça gelada.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'horses-neck',
    title: "Horse's Neck",
    tagline: 'Brandy ou bourbon, ginger ale e casca longa de limão.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['50ml de Brandy ou Bourbon', 'Ginger ale', 'Casca longa de limão', 'Gelo'],
    steps: ['Gele o copo alto;', 'Acrescente o destilado;', 'Complete com ginger ale;', 'Decore com casca de limão.'],
    notes: MIXED,
  }),
  iba({
    slug: 'irish-coffee',
    title: 'Irish Coffee',
    tagline: 'Café quente, whisky irlandês, açúcar e creme.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['50ml de Whisky irlandês', '120ml de Café quente', '1 colher de açúcar', 'Creme de leite fresco'],
    steps: ['Dissolva o açúcar no café com whisky;', 'Despeje na caneca;', 'Flote o creme por cima.'],
    notes: BUILT,
  }),
  iba({
    slug: 'kir',
    title: 'Kir',
    tagline: 'Crème de cassis e vinho branco — aperitivo francês.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['10ml de Crème de cassis', '120ml de Vinho branco seco'],
    steps: ['Coloque o cassis na taça;', 'Complete com vinho branco gelado.'],
    notes: BUILT,
  }),
  iba({
    slug: 'lemon-drop',
    title: 'Lemon Drop',
    tagline: 'Vodka, limão, triple sec e xarope — taça com açúcar.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['50ml de Vodka', '20ml de Triple sec', '20ml de Suco de limão', '1/2 dose de xarope de açúcar', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça com borda de açúcar.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'long-island-iced-tea',
    title: 'Long Island Iced Tea',
    tagline: 'Vodka, gin, rum, tequila, triple sec, limão e cola.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: [
      '15ml de Vodka',
      '15ml de Gin',
      '15ml de Rum',
      '15ml de Tequila',
      '15ml de Triple sec',
      '30ml de Suco de limão',
      'Coca-Cola',
      'Gelo',
    ],
    steps: ['Misture destilados e limão com gelo;', 'Complete com cola;', 'Sirva em copo alto.'],
    notes: MIXED,
  }),
  iba({
    slug: 'mai-tai',
    title: 'Mai Tai',
    tagline: 'Rum, curaçau, orgeat e limão — tiki clássico.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['60ml de Rum', '15ml de Curaçau', '15ml de Orgeat', '30ml de Suco de limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Despeje no copo com gelo triturado;', 'Decore com hortelã.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'mimosa',
    title: 'Mimosa',
    tagline: 'Espumante e suco de laranja — brunch clássico.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['75ml de Vinho espumante', '75ml de Suco de laranja'],
    steps: ['Misture delicadamente em taça de espumante gelada.'],
    notes: BUILT,
  }),
  iba({
    slug: 'mint-julep',
    title: 'Mint Julep',
    tagline: 'Bourbon, hortelã, açúcar e gelo triturado.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['60ml de Bourbon', '8 folhas de Hortelã', '2 colheres de açúcar', 'Gelo triturado'],
    steps: ['Macere hortelã com açúcar;', 'Acrescente bourbon e gelo;', 'Mexa até gelar a caneca.'],
    notes: MIXED,
  }),
  iba({
    slug: 'pina-colada',
    title: 'Piña Colada',
    tagline: 'Rum, coco e abacaxi — cremoso e tropical.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['50ml de Rum', '30ml de Creme de coco', '90ml de Suco de abacaxi', 'Gelo'],
    steps: ['Bata todos os ingredientes com gelo;', 'Sirva em copo alto.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'rabo-de-galo',
    title: 'Rabo de Galo',
    tagline: 'Cachaça, vermute, Cynar e bitter — clássico brasileiro IBA.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['50ml de Cachaça', '25ml de Vermute Rosso', '15ml de Cynar', '2 dashes de bitter', 'Gelo'],
    steps: ['Misture com gelo;', 'Sirva no copo old fashioned.'],
    notes: MIXED,
  }),
  iba({
    slug: 'sea-breeze',
    title: 'Sea Breeze',
    tagline: 'Vodka, cranberry e grapefruit — leve e refrescante.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['50ml de Vodka', '90ml de Suco de cranberry', '30ml de Suco de grapefruit', 'Gelo'],
    steps: ['Misture com gelo no copo alto.'],
    notes: MIXED,
  }),
  iba({
    slug: 'sex-on-the-beach',
    title: 'Sex on the Beach',
    tagline: 'Vodka, pêssego, laranja e cranberry.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: ['40ml de Vodka', '20ml de Licor de pêssego', '40ml de Suco de laranja', '40ml de Suco de cranberry', 'Gelo'],
    steps: ['Misture com gelo em copo alto.'],
    notes: MIXED,
  }),
  iba({
    slug: 'singapore-sling',
    title: 'Singapore Sling',
    tagline: 'Gin, cherry, Bénédictine, limão e soda — complexo e frutado.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: [
      '30ml de Gin',
      '15ml de Cherry Heering',
      '7ml de Bénédictine',
      'Suco de 1/2 limão',
      'Soda',
      'Gelo',
    ],
    steps: ['Bata gin, cherry, Bénédictine e limão;', 'Coe para copo alto com gelo;', 'Complete com soda.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'zombie',
    title: 'Zombie',
    tagline: 'Blend de rums, frutas e especiarias — tiki potente.',
    ibaCategory: 'Clássicos Contemporâneos',
    ingredients: [
      '45ml de Rum branco',
      '45ml de Rum escuro',
      '30ml de Rum overproof',
      '30ml de Suco de limão',
      '30ml de Suco de abacaxi',
      '15ml de Falernum',
      'Gelo',
    ],
    steps: ['Bata com gelo;', 'Despeje em copo com gelo triturado;', 'Decore com frutas.'],
    notes: SHAKEN,
  }),

  // —— Nova Era ——
  iba({
    slug: 'bees-knees',
    title: "Bee's Knees",
    tagline: 'Gin, limão e mel — sour aromático da era Proibição.',
    ibaCategory: 'Nova Era',
    ingredients: ['50ml de Gin', '25ml de Suco de limão', '20ml de Mel ou xarope de mel', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça gelada.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'bramble',
    title: 'Bramble',
    tagline: 'Gin, limão, xarope e crème de mûre — sour com amora.',
    ibaCategory: 'Nova Era',
    ingredients: ['50ml de Gin', '25ml de Suco de limão', '15ml de Xarope de açúcar', '15ml de Crème de mûre', 'Gelo triturado'],
    steps: ['Bata gin, limão e xarope;', 'Despeje em copo com gelo;', 'Regue o licor de amora por cima.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'canchanchara',
    title: 'Canchanchara',
    tagline: 'Aguardente cubana, mel e limão — ancestral cubano.',
    ibaCategory: 'Nova Era',
    ingredients: ['60ml de Aguardente ou Cachaça', '15ml de Mel', '30ml de Suco de limão', 'Gelo'],
    steps: ['Misture mel e limão;', 'Acrescente aguardente e gelo;', 'Sirva em copo curto.'],
    notes: MIXED,
  }),
  iba({
    slug: 'chartreuse-swizzle',
    title: 'Chartreuse Swizzle',
    tagline: 'Chartreuse verde, abacaxi, limão e Falernum.',
    ibaCategory: 'Nova Era',
    ingredients: ['45ml de Chartreuse verde', '60ml de Suco de abacaxi', '22ml de Suco de limão', '15ml de Falernum', 'Gelo triturado'],
    steps: ['Misture no copo com gelo triturado;', 'Swizzle até gelar bem.'],
    notes: MIXED,
  }),
  iba({
    slug: 'dark-n-stormy',
    title: "Dark 'n' Stormy",
    tagline: 'Rum escuro e ginger beer — bandeira das Bermudas.',
    ibaCategory: 'Nova Era',
    ingredients: ['60ml de Rum escuro', 'Ginger beer', 'Suco de 1/2 limão', 'Gelo'],
    steps: ['Gele o copo alto;', 'Acrescente rum e limão;', 'Complete com ginger beer.'],
    notes: MIXED,
  }),
  iba({
    slug: 'dons-special-daiquiri',
    title: "Don's Special Daiquiri",
    tagline: 'Rums, maracujá, limão e mel — tiki de Don the Beachcomber.',
    ibaCategory: 'Nova Era',
    ingredients: ['30ml de Rum jamaicano', '30ml de Rum cubano', '30ml de Suco de maracujá', '15ml de Suco de limão', '15ml de Xarope de mel', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça ou copo.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'espresso-martini',
    title: 'Espresso Martini',
    tagline: 'Vodka, espresso, licor de café e xarope.',
    ibaCategory: 'Nova Era',
    ingredients: ['50ml de Vodka', '30ml de Espresso fresco', '20ml de Licor de café', '10ml de Xarope de açúcar', 'Gelo'],
    steps: ['Bata forte com gelo;', 'Coe para taça martini;', 'Decore com grãos de café.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'fernandito',
    title: 'Fernandito',
    tagline: 'Fernet e cola — long drink argentino.',
    ibaCategory: 'Nova Era',
    ingredients: ['50ml de Fernet', 'Coca-Cola', 'Gelo'],
    steps: ['Gele o copo alto;', 'Acrescente Fernet;', 'Complete com cola.'],
    notes: MIXED,
  }),
  iba({
    slug: 'french-martini',
    title: 'French Martini',
    tagline: 'Vodka, Chambord e suco de abacaxi.',
    ibaCategory: 'Nova Era',
    ingredients: ['45ml de Vodka', '15ml de Chambord', '60ml de Suco de abacaxi', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça martini.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'gin-basil-smash',
    title: 'Gin Basil Smash',
    tagline: 'Gin, limão, xarope e manjericão macerado.',
    ibaCategory: 'Nova Era',
    ingredients: ['60ml de Gin', '30ml de Suco de limão', '20ml de Xarope de açúcar', '10 folhas de Manjericão', 'Gelo'],
    steps: ['Macere manjericão com limão e xarope;', 'Acrescente gin e gelo;', 'Bata e coe.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'grand-margarita',
    title: 'Grand Margarita',
    tagline: 'Tequila, Grand Marnier e limão — margarita premium.',
    ibaCategory: 'Nova Era',
    ingredients: ['50ml de Tequila', '20ml de Grand Marnier', '25ml de Suco de limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça com sal na borda.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'iba-tiki',
    title: 'IBA Tiki',
    tagline: 'Blend de rums, amêndoas, maracujá e abacaxi — receita IBA.',
    ibaCategory: 'Nova Era',
    ingredients: [
      '30ml de Rum branco',
      '30ml de Rum envelhecido',
      '15ml de Licor de amêndoa',
      '15ml de Maraschino',
      '30ml de Suco de maracujá',
      '30ml de Suco de abacaxi',
      '15ml de Suco de limão',
      'Gelo',
    ],
    steps: ['Bata com gelo;', 'Despeje em copo tiki com gelo triturado.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'illegal',
    title: 'Illegal',
    tagline: 'Mezcal, rum, Falernum, maraschino e limão.',
    ibaCategory: 'Nova Era',
    ingredients: ['30ml de Mezcal', '15ml de Rum branco', '15ml de Falernum', '15ml de Maraschino', '30ml de Suco de limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça gelada.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'jungle-bird',
    title: 'Jungle Bird',
    tagline: 'Rum escuro, Campari, abacaxi e limão — tiki amargo.',
    ibaCategory: 'Nova Era',
    ingredients: ['45ml de Rum escuro', '20ml de Campari', '45ml de Suco de abacaxi', '15ml de Suco de limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Despeje em copo com gelo.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'missionarys-downfall',
    title: "Missionary's Downfall",
    tagline: 'Rum, pêssego, limão, mel e hortelã — tiki refrescante.',
    ibaCategory: 'Nova Era',
    ingredients: ['60ml de Rum branco', '15ml de Brandy de pêssego', '30ml de Suco de limão', '15ml de Xarope de mel', '8 folhas de Hortelã', 'Gelo'],
    steps: ['Macere hortelã com mel e limão;', 'Acrescente rum e pêssego;', 'Bata com gelo e coe.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'naked-and-famous',
    title: 'Naked and Famous',
    tagline: 'Mezcal, Chartreuse, Aperol e limão — partes iguais.',
    ibaCategory: 'Nova Era',
    ingredients: ['22ml de Mezcal', '22ml de Chartreuse verde', '22ml de Aperol', '22ml de Suco de limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça gelada.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'new-york-sour',
    title: 'New York Sour',
    tagline: 'Whisky sour com float de vinho tinto.',
    ibaCategory: 'Nova Era',
    ingredients: ['60ml de Whisky', '30ml de Suco de limão', '20ml de Xarope de açúcar', 'Clara de 1 ovo', '30ml de Vinho tinto', 'Gelo'],
    steps: ['Bata whisky, limão, xarope e clara;', 'Coe para copo com gelo;', 'Flote o vinho por cima.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'old-cuban',
    title: 'Old Cuban',
    tagline: 'Rum envelhecido, limão, bitter, hortelã e espumante.',
    ibaCategory: 'Nova Era',
    ingredients: ['45ml de Rum envelhecido', '30ml de Suco de limão', '20ml de Xarope de açúcar', '2 dashes de bitter', '6 folhas de Hortelã', 'Espumante', 'Gelo'],
    steps: ['Macere hortelã com xarope e limão;', 'Acrescente rum e bitter; bata;', 'Coe e complete com espumante.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'paper-plane',
    title: 'Paper Plane',
    tagline: 'Bourbon, Aperol, Amaro e limão — partes iguais.',
    ibaCategory: 'Nova Era',
    ingredients: ['22ml de Bourbon', '22ml de Aperol', '22ml de Amaro', '22ml de Suco de limão', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça gelada.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'penicillin',
    title: 'Penicillin',
    tagline: 'Scotch, limão, mel e ginger — cure moderna.',
    ibaCategory: 'Nova Era',
    ingredients: ['60ml de Scotch whisky', '22ml de Suco de limão', '22ml de Xarope de mel-gengibre', '7ml de Scotch defumado', 'Gelo'],
    steps: ['Bata scotch, limão e xarope;', 'Coe para copo com gelo;', 'Float do scotch defumado.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'pisco-punch',
    title: 'Pisco Punch',
    tagline: 'Pisco, abacaxi, limão e vinho branco — San Francisco clássico.',
    ibaCategory: 'Nova Era',
    ingredients: ['60ml de Pisco', '60ml de Suco de abacaxi', '15ml de Suco de limão', '15ml de Xarope de açúcar', '30ml de Vinho branco', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça ou copo.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'porn-star-martini',
    title: 'Porn Star Martini',
    tagline: 'Vodka de baunilha, maracujá e espumante ao lado.',
    ibaCategory: 'Nova Era',
    ingredients: ['50ml de Vodka de baunilha', '25ml de Licor de maracujá', '25ml de Polpa de maracujá', '15ml de Xarope de açúcar', 'Espumante', 'Gelo'],
    steps: ['Bata vodka, licor, polpa e xarope;', 'Coe para taça;', 'Sirva espumante em shot ao lado.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'russian-spring-punch',
    title: 'Russian Spring Punch',
    tagline: 'Vodka, cassis, limão e espumante.',
    ibaCategory: 'Nova Era',
    ingredients: ['25ml de Vodka', '15ml de Crème de cassis', '25ml de Suco de limão', '15ml de Xarope de açúcar', 'Espumante', 'Gelo'],
    steps: ['Bata vodka, cassis, limão e xarope;', 'Coe para copo alto com gelo;', 'Complete com espumante.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'sherry-cobbler',
    title: 'Sherry Cobbler',
    tagline: 'Sherry, açúcar e frutas — refrescante do século XIX.',
    ibaCategory: 'Nova Era',
    ingredients: ['60ml de Sherry', '15ml de Xarope de açúcar', 'Rodelas de laranja e limão', 'Gelo triturado'],
    steps: ['Misture sherry e xarope com gelo triturado;', 'Decore com frutas.'],
    notes: MIXED,
  }),
  iba({
    slug: 'south-side',
    title: 'South Side',
    tagline: 'Gin, limão, xarope e hortelã — gin mojito seco.',
    ibaCategory: 'Nova Era',
    ingredients: ['60ml de Gin', '30ml de Suco de limão', '20ml de Xarope de açúcar', '6 folhas de Hortelã', 'Gelo'],
    steps: ['Macere hortelã com xarope e limão;', 'Acrescente gin; bata;', 'Coe para taça gelada.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'spicy-fifty',
    title: 'Spicy Fifty',
    tagline: 'Vodka, elderflower, mel e pimenta — picante e floral.',
    ibaCategory: 'Nova Era',
    ingredients: ['50ml de Vodka', '20ml de Licor de elderflower', '15ml de Xarope de mel', '25ml de Suco de limão', 'Pimenta vermelha', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça;', 'Decore com pimenta.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'spritz',
    title: 'Spritz',
    tagline: 'Espumante, bitter e soda — aperitivo veneziano.',
    ibaCategory: 'Nova Era',
    ingredients: ['60ml de Espumante', '40ml de Bitter de laranja', '20ml de Soda', 'Gelo', 'Rodela de laranja'],
    steps: ['Gele a taça de vinho;', 'Acrescente bitter e espumante;', 'Complete com soda.'],
    notes: BUILT,
  }),
  iba({
    slug: 'suffering-bastard',
    title: 'Suffering Bastard',
    tagline: 'Gin, brandy, limão, bitter e ginger ale.',
    ibaCategory: 'Nova Era',
    ingredients: ['30ml de Gin', '30ml de Brandy', '30ml de Suco de limão', '2 dashes de bitter', 'Ginger ale', 'Gelo'],
    steps: ['Bata gin, brandy, limão e bitter;', 'Despeje em copo com gelo;', 'Complete com ginger ale.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'three-dots-and-a-dash',
    title: 'Three Dots and a Dash',
    tagline: 'Rums, falernum, allspice e frutas — tiki IBA.',
    ibaCategory: 'Nova Era',
    ingredients: [
      '45ml de Rum agrícola',
      '15ml de Rum envelhecido',
      '15ml de Falernum',
      '7ml de Licor allspice',
      '30ml de Suco de laranja',
      '15ml de Suco de limão',
      '15ml de Xarope de mel',
      'Gelo',
    ],
    steps: ['Bata com gelo;', 'Despeje em copo tiki com gelo triturado.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'tipperary',
    title: 'Tipperary',
    tagline: 'Whisky irlandês, vermute e Chartreuse verde.',
    ibaCategory: 'Nova Era',
    ingredients: ['50ml de Whisky irlandês', '25ml de Vermute Rosso', '15ml de Chartreuse verde', 'Gelo'],
    steps: ['Misture com gelo;', 'Coe para taça gelada.'],
    notes: MIXED,
  }),
  iba({
    slug: 'tommys-margarita',
    title: "Tommy's Margarita",
    tagline: 'Tequila, limão e agave — margarita sem triple sec.',
    ibaCategory: 'Nova Era',
    ingredients: ['60ml de Tequila', '30ml de Suco de limão', '15ml de Agave ou xarope de açúcar', 'Gelo'],
    steps: ['Bata com gelo;', 'Sirva no copo old fashioned com gelo ou coe.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 'trinidad-sour',
    title: 'Trinidad Sour',
    tagline: 'Angostura, orgeat, limão e rye — sour inusitado.',
    ibaCategory: 'Nova Era',
    ingredients: ['45ml de Angostura bitters', '30ml de Orgeat', '30ml de Suco de limão', '15ml de Rye whisky', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça gelada.'],
    notes: SHAKEN,
  }),
  iba({
    slug: 've-n-to',
    title: 'Ve.N.To',
    tagline: 'Grappa, limão, mel e cordial de camomila — italiano moderno.',
    ibaCategory: 'Nova Era',
    ingredients: ['45ml de Grappa', '30ml de Suco de limão', '15ml de Xarope de mel', '15ml de Cordial de camomila', 'Gelo'],
    steps: ['Bata com gelo;', 'Coe para taça gelada.'],
    notes: SHAKEN,
  }),
];
